BINARY_NAME=adelApp

build:
	@go mod vendor
	@echo "Building adele..."
	@go build -o tmp/${BINARY_NAME} .
	@echo "adele built!"

run: build
	@echo "Starting adele..."
	@./tmp/${BINARY_NAME} &
	@echo "adele started!"

clean:
	@echo "Cleaning..."
	@go clean
	@rm tmp/${BINARY_NAME}
	@echo "Cleaned!"

test:
	@echo "Testing..."
	@go test ./...
	@echo "Done!"

start: run

stop:
	@echo "Stopping adele..."
	@-pkill -SIGTERM -f "./tmp/${BINARY_NAME}"
	@echo "Stopped adele!"

restart: stop start
